apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
  name: consul-ui-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8500
    nodePort: 30088
  selector:
    app: consul-cluster

